apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: functions-share
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 5Gi
